name: CICD

on:
  push:
    branches: main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7
      - uses: actions/cache@v2
        id: dep-cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          path: |
            /home/runner/.cache/pypoetry/virtualenvs
      - name: Setup dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: |
          poetry install
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7
      - uses: actions/cache@v2
        id: dep-cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          path: |
            /home/runner/.cache/pypoetry/virtualenvs
      - name: Setup dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Tests
        run: |
          poetry run poe test

